FROM serversideup/php:beta-8.3.2-fpm-nginx-alpine as base
WORKDIR /var/www/html

COPY composer.json composer.lock ./
RUN install-php-extensions bcmath
RUN composer install --no-dev --no-interaction --no-plugins --no-scripts --prefer-dist

FROM node:20 as static-assets
WORKDIR /app
COPY . .
COPY --from=base --chown=82:82 /var/www/html .
RUN npm install
RUN npm run build

FROM serversideup/php:beta-8.3.2-fpm-nginx-alpine

ARG POSTGRES_VERSION=16

WORKDIR /var/www/html
RUN apk add --no-cache postgresql${POSTGRES_VERSION}-client php-pgsql
COPY docker/production/nginx.conf /etc/nginx/conf.d/custom.conf
COPY docker/production/performance.conf /etc/nginx/server-opts.d/performance.conf

COPY --from=base /var/www/html .

COPY --chown=82:82 . .
RUN composer dump-autoload

COPY --from=static-assets --chown=82:82 /app/public/build ./public/build
COPY --chmod=755 docker/production/etc/s6-overlay/ /etc/s6-overlay/

RUN php artisan optimize

RUN echo "alias ll='ls -al'" >>/etc/bash.bashrc
RUN echo "alias a='php artisan'" >>/etc/bash.bashrc
RUN echo "alias logs='tail -f storage/logs/laravel.log'" >>/etc/bash.bashrc
